### PR TITLE
maintenance changes to reference

### PR DESCRIPTION
**Pull request by SirGoodenough**
Remove Extended References and merge them into references.
Fix json formatting so it is all indented the same, for ease of maintenance.
Update ZigBee, add TDMgr.
Adjust this and that with emoji's and spacing, other formatting fixes.
Update readme.md example to match everything else.

### CODE REVIEW

**Comment by SirGoodenough** [comment]
That should be all the extended reference retirement stuff.
You may want to delete the extended reference file all-together, but I left it in there as an empty file.

**Comment by Blade2021** [comment]
Ok, I'll take a look

**Comment by SirGoodenough** [comment]
The earliest request in here was from April 27.
Perhaps you could take a look this weekend sometime to see if this will merge?
🙏🏼

**Comment by SirGoodenough** [comment]
Well, I guess it won't be in 
June...

**Pull request merged**
